services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: frigate:latest-qualcomm
    shm_size: "256mb"
    devices:
      - qualcomm.com/device=cdi-hw-acc
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    depends_on:
      - mqtt

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - "1883:1883"
